import type { Product, Category, Banner } from "@/types";

export const demoCategories: Partial<Category>[] = [
  { name: "Gold Chains", slug: "gold-chains", metal_type: "gold", image_url: "/images/cat-chains.jpg" },
  { name: "Necklaces", slug: "necklaces", metal_type: "gold", image_url: "/images/cat-necklace.jpg" },
  { name: "Rings", slug: "rings", metal_type: "diamond", image_url: "/images/cat-rings.jpg" },
  { name: "Mangalsutra", slug: "mangalsutra", metal_type: "gold", image_url: "/images/cat-mangalsutra.jpg" },
  { name: "Bangles", slug: "bangles", metal_type: "gold", image_url: "/images/cat-bangles.jpg" },
  { name: "Earrings", slug: "earrings", metal_type: "gold", image_url: "/images/cat-earrings.jpg" },
];

export const demoProducts: Partial<Product>[] = [
  {
    id: "1",
    name: "Padmavati Antique Gold Necklace",
    slug: "padmavati-antique-gold-necklace",
    metal_type: "gold",
    purity: "22K",
    net_weight_grams: 28.4,
    gold_rate_per_gram: 6450,
    making_charges_type: "percentage",
    making_charges_value: 12,
    wastage_percentage: 6,
    stone_charges: 3200,
    gst_percentage: 3,
    discount_percentage: 4,
    tags: ["bestseller", "bridal"],
    stock_status: "in_stock",
    hallmark_number: "HUID-7QK29L",
  },
  {
    id: "2",
    name: "Kalash Temple Jhumka Earrings",
    slug: "kalash-temple-jhumka-earrings",
    metal_type: "gold",
    purity: "22K",
    net_weight_grams: 9.8,
    gold_rate_per_gram: 6450,
    making_charges_type: "percentage",
    making_charges_value: 15,
    wastage_percentage: 5,
    stone_charges: 800,
    gst_percentage: 3,
    discount_percentage: 0,
    tags: ["trending", "festival"],
    stock_status: "in_stock",
    hallmark_number: "HUID-3RP18M",
  },
  {
    id: "3",
    name: "Ekantika Diamond Solitaire Ring",
    slug: "ekantika-diamond-solitaire-ring",
    metal_type: "diamond",
    purity: "18K",
    net_weight_grams: 4.2,
    gold_rate_per_gram: 5200,
    making_charges_type: "percentage",
    making_charges_value: 18,
    wastage_percentage: 0,
    stone_charges: 42000,
    gst_percentage: 3,
    discount_percentage: 6,
    tags: ["new-arrival"],
    stock_status: "made_to_order",
    hallmark_number: "HUID-9TX55K",
  },
  {
    id: "4",
    name: "Saubhagya Bridal Mangalsutra",
    slug: "saubhagya-bridal-mangalsutra",
    metal_type: "gold",
    purity: "22K",
    net_weight_grams: 14.6,
    gold_rate_per_gram: 6450,
    making_charges_type: "percentage",
    making_charges_value: 14,
    wastage_percentage: 6,
    stone_charges: 1500,
    gst_percentage: 3,
    discount_percentage: 0,
    tags: ["bridal", "bestseller"],
    stock_status: "in_stock",
    hallmark_number: "HUID-1LM40P",
  },
];

export const demoBanners: Partial<Banner>[] = [
  {
    title: "Weighed in Trust.\nWorn for Generations.",
    subtitle: "BIS Hallmarked 916 gold — every piece verified, every gram honest.",
    cta_label: "Explore the Collection",
    cta_link: "/shop",
    image_url: "/images/hero-1.jpg",
  },
];
